<a href="https://colab.research.google.com/github/naveennekkanti1/AP21110010959-CSE336L/blob/main/Week_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1.Create a vector (array) of 1XN dimension representing N-dimensional feature vector of a sample. Write a program to compute the mean and variance of the elements present in the array. Comment what the mean and variance of sample represents.##

In [ ]:
import numpy as np
def compute_mean_and_variance(vector):
    mean = np.mean(vector)
    variance = np.var(vector)
    return mean, variance
N = int(input("Enter the dimension of the vector: "))
sample_vector = np.zeros((1, N))
print("Enter the elements of the vector separated by spaces:")
elements = input().split()
for i in range(min(N, len(elements))):
    sample_vector[0, i] = int(elements[i])
mean, variance = compute_mean_and_variance(sample_vector)
print("Sample Vector:", sample_vector)
print("Mean of the sample vector:", mean)
print("Variance of the sample vector:", variance)

Enter the dimension of the vector: 5
Enter the elements of the vector separated by spaces:
2 7 10 34 45 
Sample Vector: [[ 2.  7. 10. 34. 45.]]
Mean of the sample vector: 19.6
Variance of the sample vector: 282.64


In [ ]:
## Mean: The mean represents the average value of the elements in the sample vector. It gives us an idea of the central tendency of the data. A higher mean indicates that the values tend to be higher on average, while a lower mean indicates lower average values.
## Variance: The variance represents the spread or dispersion of the elements in the sample vector. It measures how much the elements deviate from the mean. A higher variance indicates that the data points are spread out over a wider range, while a lower variance indicates that the data points are closer to the mean.

In [ ]:
#2. Create two vectors each of dimension 1XM each representing M-dimensional feature vector of a sample. Write a program to compute the Covariance between them. Comment what Covariance between two vectors represents.

In [ ]:
import numpy as np
def compute_covariance(vector1, vector2):
    mean1 = np.mean(vector1)
    mean2 = np.mean(vector2)
    covariance = np.mean((vector1 - mean1) * (vector2 - mean2))
    return covariance
N = int(input("Enter the dimension of the vectors: "))
print("Enter values for the first vector:")
vector1 = np.array([float(input(f"Enter value {i+1}: ")) for i in range(N)])
print("Enter values for the second vector:")
vector2 = np.array([float(input(f"Enter value {i+1}: ")) for i in range(N)])
covariance = compute_covariance(vector1, vector2)
print("Covariance between vector1 and vector2:", covariance)

Enter the dimension of the vectors: 5
Enter values for the first vector:
Enter value 1: 2
Enter value 2: 56
Enter value 3: 11
Enter value 4: 23
Enter value 5: 1
Enter values for the second vector:
Enter value 1: 9
Enter value 2: 43
Enter value 3: 2
Enter value 4: 1
Enter value 5: 10
Covariance between vector1 and vector2: 254.4


In [ ]:
## The covariance between two vectors represents how much the variables in the vectors change together. If the covariance is positive, it means that when one variable increases, the other tends to increase as well. If it's negative, it means that when one variable increases, the other tends to decrease. If it's close to zero, it means that there's no linear relationship between the variables.

In [ ]:
#3.Create two vectors each of dimension 1XN. Write a program to compute the Correlation between them.Comment what the Correlation represents.

In [ ]:
import numpy as np
def compute_correlation(vector1, vector2):
    correlation_coefficient = np.corrcoef(vector1, vector2)[0, 1]
    return correlation_coefficient
N = int(input("Enter the dimension of the vectors: "))
print("Enter values for the first vector:")
vector1 = np.array([float(input(f"Enter value {i+1}: ")) for i in range(N)])
print("Enter values for the second vector:")
vector2 = np.array([float(input(f"Enter value {i+1}: ")) for i in range(N)])
correlation = compute_correlation(vector1, vector2)
print("Correlation between vector1 and vector2:", correlation)


Enter the dimension of the vectors: 3
Enter values for the first vector:
Enter value 1: 23
Enter value 2: 10
Enter value 3: 34
Enter values for the second vector:
Enter value 1: 32
Enter value 2: 1
Enter value 3: 5
Correlation between vector1 and vector2: 0.16618924316197345


In [ ]:
# The correlation between two vectors represents the degree to which they are linearly related. It measures the strength and direction of the linear relationship between the variables. If the correlation coefficient is close to 1, it indicates a strong positive linear relationship, meaning that as one variable increases, the other variable tends to increase as well. If it's close to -1, it indicates a strong negative linear relationship, meaning that as one variable increases, the other tends to decrease. If it's close to 0, it indicates little to no linear relationship between the variables.

In [ ]:
#4.Create a Matrix of MXN dimension representing the M-dimensional feature vector for N number of samples i. e (i,j)th entry of the matrix represents the ith feature of jth sample. Write a program to compute the covariance matrix and correlation matrix. Comment on takeaways from these matrixes.

In [1]:
import numpy as np

def compute_covariance_matrix(feature_matrix):
    covariance_matrix = np.cov(feature_matrix)
    return covariance_matrix
def compute_correlation_matrix(feature_matrix):
    correlation_matrix = np.corrcoef(feature_matrix)
    return correlation_matrix
def main():
    feature_matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
    covariance_matrix = compute_covariance_matrix(feature_matrix)
    print("Covariance Matrix:")
    print(covariance_matrix)
    correlation_matrix = compute_correlation_matrix(feature_matrix)
    print("\nCorrelation Matrix:")
    print(correlation_matrix)
if __name__ == "__main__":
    main()


Covariance Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
